### ISSUE TITLE
Can you Add this fork to Pub.dev

### ISSUE THREAD

**Issue by rohitsangwan01** [boskokg/flutter_blue#16]
Hey this fork seems great and almost upto date , can you please add it to Pub.dev , so that it will be easy to work with it

**Comment by trueb2** [comment]
You can use the fork using the `git` tag in pubspec.yaml

```
# Choose one flutter_blue
dependencies:
  # Original flutter blue
  flutter_blue: ^0.8.0
  
  # Cloned flutter_blue repo as sibling to current app (good for development)
  flutter_blue:
    path: ../flutter_blue
   
  # Use a specific ref from a git repo
  flutter_blue:
    git: 
      url: git@github.com:boskokg/flutter_blue
      ref: 0.13.0
````
